### PR TITLE
Allosaurus

### PR DESCRIPTION
**Pull request by steveway**

### CODE REVIEW

**Comment by aziagiles** [comment]
In the Papagayo-NG Allosaurus github branch, the Convert Phonemes from CM39 to Preston Blair currently doesn't work very well. I think it need some fixing.

**Comment by steveway** [comment]
Hello, 
Yes, those conversions can be improved.
At the moment they are quite hacky.
I've just tested this using a few of our samples and it mostly does look ok.
We should handcraft some conversions between all the different sets.

**Comment by aziagiles** [comment]
@steveway This video best describes my worry about Converting Phonemes from CM39 to Preston Blair. Lots of missing conversions.

https://user-images.githubusercontent.com/9162114/125488142-06600c6d-2c91-4249-beb6-5c9258e876a2.mp4

**Comment by steveway** [comment]
It looks like you did not click on "Convert Phonemes" after you selected the Preston Blair phonemes.
It will only do the conversion when you click on that, I'll likely move the button somewhere else from up there in the action bar.

**Comment by aziagiles** [comment]
@steveway I actually clicked ''Convert Phonemes'', the first second of the audio converted well but the rest keeps indicating Missing Phonemes. I'm on a Windows 10 computer.

**Comment by Hunanbean** [comment]
Just wanted to add, I am experiencing the same issue. Worked for about the first half, then started throwing missing phoneme messages. Also, I do not know if this is expected behavior, but the phoneme display never changes. After you hit convert, the only way to know it converted is to either look at the output of the exported file, or to press play and watch the appropriate face. Windows 10 here too.

Thank you

**Comment by steveway** [comment]
I believe this should be mostly fixed in the new 1.6.3 Release thanks to commit ce4ee258feaf3cf62d11af460810c6dbf4d4022f

**Pull request merged**
